### ISSUE TITLE
Sprint 2 - Tarea 3.1 - Verificar el modelado del movimiento de dinero como una clase de Java

### ISSUE THREAD

**Issue by Gru19mntc** [Gru19mntc/Proyecto-Ciclo-3-Grupo-19-ACME#10]
- [x] Es posible crear una nueva instancia de la clase "MovimientoDinero" (Verificar en la clase main)
- [x] Es posible leer y modificar el monto del movimiento (Verificar en la clase main)
- [x] Es posible crear montos positivos y negativos (Verificar en la clase main)
- [x] Es posible leer y modificar el concepto del movimiento (Verificar en la clase main)
- [x] Es posible definir qué usuario fue encargado de registrar el movimiento (Verificar en la clase main)

**Comment by Juansis99** [comment]
Se verifica correctamente cada una de las actividades esperada por la clase.
