### ISSUE TITLE
Sprint 3 - Tarea 3 - Actualizar el diagrama de clases UML

### ISSUE THREAD

**Issue by Gru19mntc** [Gru19mntc/Proyecto-Ciclo-3-Grupo-19-ACME#19]

**Comment by Juansis99** [comment]
Se actualiza el diagrama de clases UML en la siguiente ruta:
https://lucid.app/lucidchart/48e7e61c-9cec-4862-a19d-f1b7ff72373f/edit?viewport_loc=-25%2C-78%2C1961%2C986%2CHWEp-vi-RSFO&invitationId=inv_5501c204-f732-4948-8b42-1fcd78f27947#

![Image](https://user-images.githubusercontent.com/104040617/189462592-728aeb30-ea6c-477c-9e6e-b423eba06f53.png)
