### ISSUE TITLE
Sprint 3 - Tarea 4 - Crear el modelo entidad-relacion para el proyecto

### ISSUE THREAD

**Issue by Gru19mntc** [Gru19mntc/Proyecto-Ciclo-3-Grupo-19-ACME#20]

**Comment by Joaokld3** [comment]
https://lucid.app/documents/view/d32c4d62-58be-4c92-8016-cd853d4303b2

![image](https://user-images.githubusercontent.com/107194287/189384519-2d5e42f9-e46f-4ae4-908b-629806dc6f8f.png)
