### ISSUE TITLE
Sprint 4 - Tarea 4 - Crear una interfaz para visualizar todos los movimientos de dinero de una empresa

### ISSUE THREAD

**Issue by Gru19mntc** [Gru19mntc/Proyecto-Ciclo-3-Grupo-19-ACME#29]
- [x] Es posible visualizar una lista de los movimientos de dinero de la empresa y un total de todos los movimientos.

**Comment by Juansis99** [comment]
Se crea la interfaz funcional para consultar los movimientos de dinero de una empresa especifica, pendiente la suma del total de los movimientos.

**Comment by Juansis99** [comment]
Total de movimientos OK
