### ISSUE TITLE
Sprint 2 - Tarea 3 - Modelar el movimiento de dinero como una clase de Java

### ISSUE THREAD

**Issue by Gru19mntc** [Gru19mntc/Proyecto-Ciclo-3-Grupo-19-ACME#9]
- [x] Es posible crear una nueva instancia de la clase "MovimientoDinero" (Crear el constructor)
- [x] Es posible leer y modificar el monto del movimiento (Crear atributo, getter y setter)
- [x] Es posible crear montos positivos y negativos (Crear atributo, getter y setter)
- [x] Es posible leer y modificar el concepto del movimiento (Crear atributo, getter y setter)
- [x] Es posible definir qué usuario fue encargado de registrar el movimiento (Crear atributo, getter y setter)

**Comment by Juansis99** [comment]
Se añade a la clase "Empleado" dentro del constructor vacío la inicialización del nombre del empleado para validar el correcto funcionamiento de la clase "MovimientoDinero".
